outmed_fee_stt_rt_d;
SELECT
     random_string(32) AS OUTMED_FEE_STT_RT_ID,
     random_string(32) AS RID,
     now() AS STT_TIME,
     now() AS CRTE_TIME,
     now() AS UPDT_TIME,
     T2.PROV_ADMDVS_ID AS PROV_ADMDVS,
     T2.PROV_ADMDVS_NAME AS PROV_ADMDVS_NAME,
     T1.DB_INSUTYPE AS INSUTYPE,
     T1.DB_INSUTYPE_NAME AS INSUTYPE_NAME,
     T1.DB_SETL_PSNTIME AS SETL_PSNTIME,
     T1.DB_FUND_PAY AS FUND_PAY,
     T1.DB_MEDFEE_SUMAMT AS MEDFEE_SUMAMT,
     T1.DB_IPT_TOTL_DAYS AS IPT_TOTL_DAYS
    FROM
    (
     SELECT
         S.INSU_ADMDVS AS DB_ADMDVS,
         S.INSUTYPE AS DB_INSUTYPE,
         CASE WHEN S.INSUTYPE IN ('310','320','330','340','350','360','370','399','510') THEN '城镇职工' WHEN S.INSUTYPE IN ('380','390','391','392') THEN '城乡居民' ELSE '' END AS DB_INSUTYPE_NAME,
         ROUND(COUNT(S.SETL_ID),2) AS DB_SETL_PSNTIME,
         SUM( S.FUND_PAY_SUMAMT ) AS DB_FUND_PAY,
         SUM( S.MEDFEE_SUMAMT ) AS DB_MEDFEE_SUMAMT,
         ROUND(SUM(DATEDIFF(S.ENDDATE,S.BEGNDATE)),2) AS DB_IPT_TOTL_DAYS
     FROM
         setl_d S
     WHERE
         S.TIME>='{}' and S.BIZ_DATE<='{}'
         S.VALI_FLAG = '1'
     AND substr(S.INSU_ADMDVS,1,2) <> substr(S.FIX_BLNG_ADMDVS,1,2)
     GROUP BY S.INSU_ADMDVS,S.INSUTYPE
     ) T1
     LEFT JOIN
     dim_pub_admdvs_ds T2
     ON  T1.DB_ADMDVS = T2.ADMDVS;
outmed_setl_dise_rt_d;
SELECT random_string(32) AS OUTMED_DISE_RT_ID,
    random_string(32) AS RID,
    now() AS STT_TIME,
    now() AS CRTE_TIME,
    now() AS UPDT_TIME,
    T2.PROV_ADMDVS_ID AS PROV_ADMDVS,
    T2.PROV_ADMDVS_NAME AS PROV_ADMDVS_NAME,
    T1.DB_DISECODE AS DISECODE,
    T1.DB_DISENAME AS DISENAME,
    T1.DB_SETL_PSNTIME AS SETL_PSNTIME
    FROM
    (
     SELECT S.INSU_ADMDVS AS DB_ADMDVS,
         A.DIAG_CODE AS DB_DISECODE,
         A.DISE_NAME AS DB_DISENAME,
         COUNT( S.SETL_ID ) AS DB_SETL_PSNTIME
     FROM setl_d S
     WHERE S.TIME>='{}' and S.TIME<='{}' AND S.VALI_FLAG = '1'
     AND substr(S.INSU_ADMDVS,1,2) <> substr(S.FIX_BLNG_ADMDVS,1,2)
     LEFT JOIN setl_diag_list_d A ON  S.MDTRT_ID = A.MDTRT_ID
     GROUP BY S.INSU_ADMDVS,A.DISE_NO,A.DISE_NAME
    ) T1
    LEFT JOIN dim_pub_admdvs_ds T2 ON  T1.DB_ADMDVS = T2.ADMDVS;